<?php

return [
    /*
    |--------------------------------------------------------------------------
    | PBC System Configuration
    |--------------------------------------------------------------------------
    */

    'file_upload' => [
        'max_size' => env('MAX_FILE_UPLOAD_SIZE', 10240), // KB
        'allowed_types' => explode(',', env('ALLOWED_FILE_TYPES', 'pdf,doc,docx,xls,xlsx,jpg,jpeg,png,txt,csv')),
        'max_files_per_request' => env('MAX_FILES_PER_REQUEST', 10),
    ],

    'reminders' => [
        'default_days' => env('DEFAULT_REMINDER_DAYS', 3),
        'auto_enabled' => env('AUTO_REMINDER_ENABLED', true),
        'types' => ['initial', 'follow_up', 'urgent', 'final_notice'],
    ],

    'company' => [
        'name' => env('COMPANY_NAME', 'Audit Firm'),
        'address' => env('COMPANY_ADDRESS', ''),
        'phone' => env('COMPANY_PHONE', ''),
        'email' => env('COMPANY_EMAIL', ''),
    ],

    'system' => [
        'overdue_threshold' => env('PBC_OVERDUE_THRESHOLD', 1), // days
        'warning_threshold' => env('PBC_WARNING_THRESHOLD', 3), // days
        'auto_archive_days' => env('PBC_AUTO_ARCHIVE_DAYS', 365),
        'max_document_versions' => env('PBC_MAX_DOCUMENT_VERSIONS', 10),
    ],

    'notifications' => [
        'email' => env('NOTIFICATION_EMAIL', 'notifications@example.com'),
        'send_email' => env('SEND_EMAIL_NOTIFICATIONS', true),
        'send_sms' => env('SEND_SMS_NOTIFICATIONS', false),
    ],

    'security' => [
        'password_min_length' => env('PASSWORD_MIN_LENGTH', 8),
        'require_special_chars' => env('PASSWORD_REQUIRE_SPECIAL_CHARS', true),
        'require_numbers' => env('PASSWORD_REQUIRE_NUMBERS', true),
        'require_uppercase' => env('PASSWORD_REQUIRE_UPPERCASE', true),
        'lockout_attempts' => env('ACCOUNT_LOCKOUT_ATTEMPTS', 5),
        'lockout_duration' => env('ACCOUNT_LOCKOUT_DURATION', 30), // minutes
    ],

    'audit' => [
        'enabled' => env('ENABLE_AUDIT_LOGGING', true),
        'retention_days' => env('AUDIT_LOG_RETENTION_DAYS', 2555), // 7 years
        'log_user_activities' => env('LOG_USER_ACTIVITIES', true),
        'log_document_activities' => env('LOG_DOCUMENT_ACTIVITIES', true),
    ],

    'reports' => [
        'default_format' => env('DEFAULT_REPORT_FORMAT', 'pdf'),
        'logo_path' => env('REPORT_LOGO_PATH', 'images/company-logo.png'),
        'footer_text' => env('REPORT_FOOTER_TEXT', 'Generated by PBC Checklist Management System'),
    ],

    'features' => [
        'document_preview' => env('ENABLE_DOCUMENT_PREVIEW', true),
        'bulk_operations' => env('ENABLE_BULK_OPERATIONS', true),
        'email_templates' => env('ENABLE_EMAIL_TEMPLATES', true),
        'custom_fields' => env('ENABLE_CUSTOM_FIELDS', true),
        'workflow_automation' => env('ENABLE_WORKFLOW_AUTOMATION', true),
    ],

    'ui' => [
        'theme_primary_color' => env('THEME_PRIMARY_COLOR', '#3B82F6'),
        'theme_secondary_color' => env('THEME_SECONDARY_COLOR', '#10B981'),
        'theme_accent_color' => env('THEME_ACCENT_COLOR', '#F59E0B'),
        'dark_mode_enabled' => env('DARK_MODE_ENABLED', true),
        'sidebar_collapsed' => env('SIDEBAR_COLLAPSED', false),
    ],

    'performance' => [
        'paginate_per_page' => env('PAGINATE_PER_PAGE', 25),
        'search_results_limit' => env('SEARCH_RESULTS_LIMIT', 100),
        'cache_ttl' => env('CACHE_TTL', 3600), // seconds
        'enable_query_cache' => env('ENABLE_QUERY_CACHE', true),
    ],
];
